# Generated by Django 4.2.28 on 2026-02-20 07:23

from django.db import migrations, models


def backfill_ticket_numbers(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    for t in Ticket.objects.filter(ticket_number__isnull=True):
        t.ticket_number = f"TKT-{t.id:06d}"
        t.save(update_fields=["ticket_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_ticket_numbers, migrations.RunPython.noop),
    ]
