# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_add_ticket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/%Y/%m/"),
        ),
    ]
