# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


def migrate_images(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    TicketImage = apps.get_model("tickets", "TicketImage")
    for ticket in Ticket.objects.exclude(image__isnull=True).exclude(image=""):
        TicketImage.objects.create(ticket=ticket, image=ticket.image)


def reverse_migrate(apps, schema_editor):
    TicketImage = apps.get_model("tickets", "TicketImage")
    Ticket = apps.get_model("tickets", "Ticket")
    for ticket in Ticket.objects.all():
        first = TicketImage.objects.filter(ticket=ticket).order_by("id").first()
        if first:
            ticket.image = first.image
            ticket.save(update_fields=["image"])


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_add_ticket_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="tickets/%Y/%m/")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="tickets.ticket")),
            ],
        ),
        migrations.RunPython(migrate_images, reverse_migrate),
        migrations.RemoveField(
            model_name="ticket",
            name="image",
        ),
    ]
